# Generated by Django 4.2 on 2025-05-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paper",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
        migrations.AddField(
            model_name="paper",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="creation_year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="paper",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="paper",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="paper",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
