# Generated by Django 4.2 on 2025-05-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0003_paper_uploader_name_tag_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="creation_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
